# Importing data

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

from feature_eng import preprocess
df = pd.read_csv("~/ML/Data/house_prices/train.csv")

In [3]:
df['Street']

0       Pave
1       Pave
2       Pave
3       Pave
4       Pave
        ...
1455    Pave
1456    Pave
1457    Pave
1458    Pave
1459    Pave
Name: Street, Length: 1460, dtype: object

In [95]:
x_train,x_test = train_test_split(df,test_size=0.2,random_state=42)

In [5]:
x_train.dtypes

Id                 int64
MSSubClass         int64
MSZoning          object
LotFrontage      float64
LotArea            int64
                  ...
MoSold             int64
YrSold             int64
SaleType          object
SaleCondition     object
SalePrice          int64
Length: 81, dtype: object

In [6]:
x_train.shape

(1168, 81)

In [7]:
x_train.isna().mean().sort_values(ascending=False)

PoolQC           0.994863
MiscFeature      0.960616
Alley            0.936644
Fence            0.800514
MasVnrType       0.584760
                   ...
MoSold           0.000000
YrSold           0.000000
SaleType         0.000000
SaleCondition    0.000000
SalePrice        0.000000
Length: 81, dtype: float64

# Looking for NaN features

In [8]:
x_train['HouseStyle'].value_counts().mean()

np.float64(146.0)

In [9]:
x_train.isna().mean()[x_train.isna().mean() > 0.5]

Alley          0.936644
MasVnrType     0.584760
PoolQC         0.994863
Fence          0.800514
MiscFeature    0.960616
dtype: float64

In [10]:
x_train['MiscFeature'].isna().mean()

np.float64(0.9606164383561644)

In [11]:
x_train['PoolQC'].isna().mean()

np.float64(0.9948630136986302)

In [12]:
x_train['Alley'].isna().mean()

np.float64(0.9366438356164384)

In [13]:
x_train.loc[:,['Fence','FireplaceQu']]

      Fence FireplaceQu
254     NaN         NaN
1066    NaN          TA
638   MnPrv         NaN
799   MnPrv          TA
380     NaN          Gd
...     ...         ...
1095    NaN          Gd
1130  MnPrv          TA
1294    NaN         NaN
860   GdPrv          Gd
1126    NaN          TA

[1168 rows x 2 columns]

In [14]:
x_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1168 entries, 254 to 1126
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1168 non-null   int64
 1   MSSubClass     1168 non-null   int64
 2   MSZoning       1168 non-null   object
 3   LotFrontage    951 non-null    float64
 4   LotArea        1168 non-null   int64
 5   Street         1168 non-null   object
 6   Alley          74 non-null     object
 7   LotShape       1168 non-null   object
 8   LandContour    1168 non-null   object
 9   Utilities      1168 non-null   object
 10  LotConfig      1168 non-null   object
 11  LandSlope      1168 non-null   object
 12  Neighborhood   1168 non-null   object
 13  Condition1     1168 non-null   object
 14  Condition2     1168 non-null   object
 15  BldgType       1168 non-null   object
 16  HouseStyle     1168 non-null   object
 17  OverallQual    1168 non-null   int64
 18  OverallCond    1168 non-null   int64
 19  YearBuilt      1168 non-null   int64
 20  YearRemodAdd   1168 non-null   int64
 21  RoofStyle      1168 non-null   object
 22  RoofMatl       1168 non-null   object
 23  Exterior1st    1168 non-null   object
 24  Exterior2nd    1168 non-null   object
 25  MasVnrType     485 non-null    object
 26  MasVnrArea     1162 non-null   float64
 27  ExterQual      1168 non-null   object
 28  ExterCond      1168 non-null   object
 29  Foundation     1168 non-null   object
 30  BsmtQual       1140 non-null   object
 31  BsmtCond       1140 non-null   object
 32  BsmtExposure   1140 non-null   object
 33  BsmtFinType1   1140 non-null   object
 34  BsmtFinSF1     1168 non-null   int64
 35  BsmtFinType2   1140 non-null   object
 36  BsmtFinSF2     1168 non-null   int64
 37  BsmtUnfSF      1168 non-null   int64
 38  TotalBsmtSF    1168 non-null   int64
 39  Heating        1168 non-null   object
 40  HeatingQC      1168 non-null   object
 41  CentralAir     1168 non-null   object
 42  Electrical     1167 non-null   object
 43  1stFlrSF       1168 non-null   int64
 44  2ndFlrSF       1168 non-null   int64
 45  LowQualFinSF   1168 non-null   int64
 46  GrLivArea      1168 non-null   int64
 47  BsmtFullBath   1168 non-null   int64
 48  BsmtHalfBath   1168 non-null   int64
 49  FullBath       1168 non-null   int64
 50  HalfBath       1168 non-null   int64
 51  BedroomAbvGr   1168 non-null   int64
 52  KitchenAbvGr   1168 non-null   int64
 53  KitchenQual    1168 non-null   object
 54  TotRmsAbvGrd   1168 non-null   int64
 55  Functional     1168 non-null   object
 56  Fireplaces     1168 non-null   int64
 57  FireplaceQu    621 non-null    object
 58  GarageType     1104 non-null   object
 59  GarageYrBlt    1104 non-null   float64
 60  GarageFinish   1104 non-null   object
 61  GarageCars     1168 non-null   int64
 62  GarageArea     1168 non-null   int64
 63  GarageQual     1104 non-null   object
 64  GarageCond     1104 non-null   object
 65  PavedDrive     1168 non-null   object
 66  WoodDeckSF     1168 non-null   int64
 67  OpenPorchSF    1168 non-null   int64
 68  EnclosedPorch  1168 non-null   int64
 69  3SsnPorch      1168 non-null   int64
 70  ScreenPorch    1168 non-null   int64
 71  PoolArea       1168 non-null   int64
 72  PoolQC         6 non-null      object
 73  Fence          233 non-null    object
 74  MiscFeature    46 non-null     object
 75  MiscVal        1168 non-null   int64
 76  MoSold         1168 non-null   int64
 77  YrSold         1168 non-null   int64
 78  SaleType       1168 non-null   object
 79  SaleCondition  1168 non-null   object
 80  SalePrice      1168 non-null   int64
dtypes: float64(3), int64(35), object(43)
memory usage: 748.2+ KB

In [15]:
x_train.loc[:,['PoolArea','PoolQC']][x_train['PoolArea']== 0 ] # if poolArea == 0 , we don't have pool so PoolQC is NaN

      PoolArea PoolQC
254          0    NaN
1066         0    NaN
638          0    NaN
799          0    NaN
380          0    NaN
...        ...    ...
1095         0    NaN
1130         0    NaN
1294         0    NaN
860          0    NaN
1126         0    NaN

[1162 rows x 2 columns]

In [16]:
x_train.loc[:,['Alley']] # NaN means there is no alley

     Alley
254    NaN
1066   NaN
638    NaN
799    NaN
380   Pave
...    ...
1095   NaN
1130   NaN
1294   NaN
860    NaN
1126   NaN

[1168 rows x 1 columns]

In [17]:
x_train.loc[:,['Fence']] # NaN means there is no fence

      Fence
254     NaN
1066    NaN
638   MnPrv
799   MnPrv
380     NaN
...     ...
1095    NaN
1130  MnPrv
1294    NaN
860   GdPrv
1126    NaN

[1168 rows x 1 columns]

In [18]:
x_train.loc[:,'MiscFeature']

254     NaN
1066    NaN
638     NaN
799     NaN
380     NaN
       ...
1095    NaN
1130    NaN
1294    NaN
860     NaN
1126    NaN
Name: MiscFeature, Length: 1168, dtype: object

In [19]:
x_train.loc[:,['MasVnrType','MasVnrArea']][x_train.MasVnrType == 'None'] # No area == No type
x_train['MasVnrType'][x_train.MasVnrType == 'None'].sum()

0

In [20]:
x_train.loc[:,['FireplaceQu','Fireplaces']][x_train['Fireplaces'] > 0 ] # 0 Fireplace == NaN quality

     FireplaceQu  Fireplaces
1066          TA           1
799           TA           2
380           Gd           1
86            Gd           1
265           TA           1
...          ...         ...
1044          Gd           1
1095          Gd           1
1130          TA           2
860           Gd           1
1126          TA           1

[621 rows x 2 columns]

In [21]:
x_train.loc[:,['Fireplaces','FireplaceQu']][x_train.Fireplaces > 0].isna().sum() # if there is fireplace, it must have quality

Fireplaces     0
FireplaceQu    0
dtype: int64

In [22]:
x_train.loc[:,['MasVnrType','MasVnrArea']][x_train.MasVnrType.isna() & x_train.MasVnrArea == 0] # NaN in VnrType should be treated as 'None' class

     MasVnrType  MasVnrArea
254         NaN         0.0
1066        NaN         0.0
638         NaN         0.0
799     BrkFace       252.0
380         NaN         0.0
...         ...         ...
1095        NaN         0.0
1130        NaN         0.0
1294        NaN         0.0
860         NaN         0.0
1126    BrkFace       130.0

[1163 rows x 2 columns]

In [23]:
x_train.loc[:,['MasVnrType','MasVnrArea']][x_train.MasVnrType.isna() & x_train.MasVnrArea.isna()] # We have missing data

     MasVnrType  MasVnrArea
936         NaN         NaN
973         NaN         NaN
650         NaN         NaN
1278        NaN         NaN
234         NaN         NaN
977         NaN         NaN

In [24]:
x_train.loc[:,['MasVnrType','MasVnrArea']][x_train.MasVnrType.isna() & x_train.MasVnrArea > 0] # We do have Vnr but we don't know type ( missing data )

     MasVnrType  MasVnrArea
624         NaN       288.0
1230        NaN         1.0
1300        NaN       344.0
773         NaN         1.0
1334        NaN       312.0

In [25]:
x_train.loc[x_train['MasVnrType'].isna() & (x_train['MasVnrArea'] == 0), 'MasVnrType'] = 'None'
x_test.loc[x_test['MasVnrType'].isna() & (x_test['MasVnrArea'] == 0), 'MasVnrType'] = 'None'

In [26]:
x_train['MasVnrType']

254        None
1066       None
638        None
799     BrkFace
380        None
         ...
1095       None
1130       None
1294       None
860        None
1126    BrkFace
Name: MasVnrType, Length: 1168, dtype: object

# Handling NaN ( #1 )

In [27]:
x_train.loc[x_train['MasVnrType'].isna() & x_train['MasVnrArea'].isna() , 'MasVnrType'] = 'None'
x_train.loc[x_train['MasVnrType'].isna() & x_train['MasVnrArea'].isna() , 'MasVnrArea'] = 0

In [28]:
x_test.loc[x_test['MasVnrType'].isna() & x_test['MasVnrArea'].isna() , 'MasVnrType'] = 'None'
x_test.loc[x_test['MasVnrType'].isna() & x_test['MasVnrArea'].isna() , 'MasVnrArea'] = 0

In [29]:
# x_train.loc[:,['MasVnrType','MasVnrArea']][x_train.MasVnrType.isna() & x_train.MasVnrArea > 0] # We do have Vnr but we don't know type ( missing data )
x_train['MasVnrType'].value_counts()

MasVnrType
None       678
BrkFace    366
Stone      106
BrkCmn      13
Name: count, dtype: int64

In [30]:
x_train.loc[x_train['MasVnrType'].isna() & x_train['MasVnrArea'] > 0, 'MasVnrType'] = 'BrkFace'

In [31]:
x_test.loc[x_test['MasVnrType'].isna() & x_test['MasVnrArea'] > 0, 'MasVnrType'] = 'BrkFace'

In [32]:
x_train.loc[(x_train['MasVnrType'] == 'None') & x_train['MasVnrArea'].isna(), 'MasVnrArea'] = 0

In [33]:
x_test.loc[(x_test['MasVnrType'] == 'None') & x_test['MasVnrArea'].isna(), 'MasVnrArea'] = 0

In [34]:
x_train.MasVnrArea.value_counts()

MasVnrArea
0.0      680
180.0      7
108.0      7
16.0       6
200.0      6
        ...
423.0      1
426.0      1
616.0      1
603.0      1
309.0      1
Name: count, Length: 286, dtype: int64

In [35]:
x_train.loc[:,['BsmtCond','BsmtExposure']][x_train.BsmtExposure.isna()]

     BsmtCond BsmtExposure
342       NaN          NaN
1048      NaN          NaN
156       NaN          NaN
778       NaN          NaN
705       NaN          NaN
39        NaN          NaN
553       NaN          NaN
1035      NaN          NaN
362       NaN          NaN
533       NaN          NaN
182       NaN          NaN
102       NaN          NaN
1179      NaN          NaN
1000      NaN          NaN
90        NaN          NaN
1412      NaN          NaN
1090      NaN          NaN
868       NaN          NaN
1011      NaN          NaN
17        NaN          NaN
1218      NaN          NaN
749       NaN          NaN
1045      NaN          NaN
1321      NaN          NaN
392       NaN          NaN
520       NaN          NaN
897       NaN          NaN
646       NaN          NaN

In [36]:
x_train.isna().mean()[x_train.isna().mean() > 0].sort_values(ascending=False)

PoolQC          0.994863
MiscFeature     0.960616
Alley           0.936644
Fence           0.800514
FireplaceQu     0.468322
LotFrontage     0.185788
GarageType      0.054795
GarageFinish    0.054795
GarageQual      0.054795
GarageYrBlt     0.054795
GarageCond      0.054795
BsmtQual        0.023973
BsmtFinType2    0.023973
BsmtFinType1    0.023973
BsmtCond        0.023973
BsmtExposure    0.023973
Electrical      0.000856
dtype: float64

# Handling NaN ( #2 )

In [37]:
x_train.loc[:,['BsmtCond','BsmtExposure','BsmtExposure','BsmtFinSF1','BsmtFinType1','BsmtFinSF2','BsmtFinType2']].isna().mean()

BsmtCond        0.023973
BsmtExposure    0.023973
BsmtExposure    0.023973
BsmtFinSF1      0.000000
BsmtFinType1    0.023973
BsmtFinSF2      0.000000
BsmtFinType2    0.023973
dtype: float64

In [38]:
x_train.loc[:,['BsmtCond','BsmtExposure','BsmtExposure','BsmtFinSF1','BsmtFinType1','BsmtFinSF2','BsmtFinType2','TotalBsmtSF']][x_train.BsmtCond.isna() | x_train.BsmtQual.isna()]

,BsmtCond,BsmtExposure,BsmtExposure,BsmtFinSF1,BsmtFinType1,BsmtFinSF2,BsmtFinType2,TotalBsmtSF
342,NaN,NaN,NaN,0,NaN,0,NaN,0
1048,NaN,NaN,NaN,0,NaN,0,NaN,0
156,NaN,NaN,NaN,0,NaN,0,NaN,0
778,NaN,NaN,NaN,0,NaN,0,NaN,0
705,NaN,NaN,NaN,0,NaN,0,NaN,0
39,NaN,NaN,NaN,0,NaN,0,NaN,0
553,NaN,NaN,NaN,0,NaN,0,NaN,0
1035,NaN,NaN,NaN,0,NaN,0,NaN,0
362,NaN,NaN,NaN,0,NaN,0,NaN,0
533,NaN,NaN,NaN,0,NaN,0,NaN,0
182,NaN,NaN,NaN,0,NaN,0,NaN,0
102,NaN,NaN,NaN,0,NaN,0,NaN,0
1179,NaN,NaN,NaN,0,NaN,0,NaN,0
1000,NaN,NaN,NaN,0,NaN,0,NaN,0
90,NaN,NaN,NaN,0,NaN,0,NaN,0
1412,NaN,NaN,NaN,0,NaN,0,NaN,0
1090,NaN,NaN,NaN,0,NaN,0,NaN,0
868,NaN,NaN,NaN,0,NaN,0,NaN,0
1011,NaN,NaN,NaN,0,NaN,0,NaN,0
17,NaN,NaN,NaN,0,NaN,0,NaN,0
1218,NaN,NaN,NaN,0,NaN,0,NaN,0
749,NaN,NaN,NaN,0,NaN,0,NaN,0
1045,NaN,NaN,NaN,0,NaN,0,NaN,0
1321,NaN,NaN,NaN,0,NaN,0,NaN,0
392,NaN,NaN,NaN,0,NaN,0,NaN,0
520,NaN,NaN,NaN,0,NaN,0,NaN,0
897,NaN,NaN,NaN,0,NaN,0,NaN,0
646,NaN,NaN,NaN,0,NaN,0,NaN,0

In [39]:
x_train.loc[:,['BsmtCond','BsmtExposure','BsmtExposure','BsmtFinSF1','BsmtFinType1','BsmtFinSF2','BsmtFinType2']][x_train.BsmtFinType2.isna()]

,BsmtCond,BsmtExposure,BsmtExposure,BsmtFinSF1,BsmtFinType1,BsmtFinSF2,BsmtFinType2
342,NaN,NaN,NaN,0,NaN,0,NaN
1048,NaN,NaN,NaN,0,NaN,0,NaN
156,NaN,NaN,NaN,0,NaN,0,NaN
778,NaN,NaN,NaN,0,NaN,0,NaN
705,NaN,NaN,NaN,0,NaN,0,NaN
39,NaN,NaN,NaN,0,NaN,0,NaN
553,NaN,NaN,NaN,0,NaN,0,NaN
1035,NaN,NaN,NaN,0,NaN,0,NaN
362,NaN,NaN,NaN,0,NaN,0,NaN
533,NaN,NaN,NaN,0,NaN,0,NaN
182,NaN,NaN,NaN,0,NaN,0,NaN
102,NaN,NaN,NaN,0,NaN,0,NaN
1179,NaN,NaN,NaN,0,NaN,0,NaN
1000,NaN,NaN,NaN,0,NaN,0,NaN
90,NaN,NaN,NaN,0,NaN,0,NaN
1412,NaN,NaN,NaN,0,NaN,0,NaN
1090,NaN,NaN,NaN,0,NaN,0,NaN
868,NaN,NaN,NaN,0,NaN,0,NaN
1011,NaN,NaN,NaN,0,NaN,0,NaN
17,NaN,NaN,NaN,0,NaN,0,NaN
1218,NaN,NaN,NaN,0,NaN,0,NaN
749,NaN,NaN,NaN,0,NaN,0,NaN
1045,NaN,NaN,NaN,0,NaN,0,NaN
1321,NaN,NaN,NaN,0,NaN,0,NaN
392,NaN,NaN,NaN,0,NaN,0,NaN
520,NaN,NaN,NaN,0,NaN,0,NaN
897,NaN,NaN,NaN,0,NaN,0,NaN
646,NaN,NaN,NaN,0,NaN,0,NaN

In [40]:
# Where TotalBsmtSF is 0 (no basement), recode NAs to 'None'
bsmt_cat_cols = ['BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2']

for col in bsmt_cat_cols:
    x_train.loc[(x_train['TotalBsmtSF'] == 0) & x_train[col].isna(), col] = 'None'
    x_test.loc[(x_test['TotalBsmtSF'] == 0) & x_test[col].isna(), col] = 'None'

In [41]:
x_train.loc[:,['BsmtCond','BsmtExposure','BsmtExposure','BsmtFinSF1','BsmtFinType1','BsmtFinSF2','BsmtFinType2']].isna().mean()

BsmtCond        0.0
BsmtExposure    0.0
BsmtExposure    0.0
BsmtFinSF1      0.0
BsmtFinType1    0.0
BsmtFinSF2      0.0
BsmtFinType2    0.0
dtype: float64

In [42]:
x_train.isna().mean().sort_values(ascending=False)

PoolQC           0.994863
MiscFeature      0.960616
Alley            0.936644
Fence            0.800514
FireplaceQu      0.468322
                   ...
MoSold           0.000000
YrSold           0.000000
SaleType         0.000000
SaleCondition    0.000000
SalePrice        0.000000
Length: 81, dtype: float64

In [43]:
x_train.loc[:,['GarageType','GarageFinish','GarageQual','GarageCond','GarageArea','GarageYrBlt']][x_train.GarageArea == 0]

     GarageType GarageFinish GarageQual GarageCond  GarageArea  GarageYrBlt
638         NaN          NaN        NaN        NaN           0          NaN
210         NaN          NaN        NaN        NaN           0          NaN
48          NaN          NaN        NaN        NaN           0          NaN
155         NaN          NaN        NaN        NaN           0          NaN
1030        NaN          NaN        NaN        NaN           0          NaN
...         ...          ...        ...        ...         ...          ...
520         NaN          NaN        NaN        NaN           0          NaN
241         NaN          NaN        NaN        NaN           0          NaN
562         NaN          NaN        NaN        NaN           0          NaN
1337        NaN          NaN        NaN        NaN           0          NaN
1123        NaN          NaN        NaN        NaN           0          NaN

[64 rows x 6 columns]

In [44]:
garage_cols = ['GarageType','GarageFinish','GarageQual','GarageCond']

for col in garage_cols:
    x_train.loc[(x_train['GarageArea'] == 0) & x_train[col].isna(), col] = 'None'
    x_test.loc[(x_test['GarageArea'] == 0) & x_test[col].isna(), col] = 'None'

In [45]:
x_train.loc[:,['GarageType','GarageFinish','GarageQual','GarageCond','GarageArea','GarageYrBlt']].isna().mean()

GarageType      0.000000
GarageFinish    0.000000
GarageQual      0.000000
GarageCond      0.000000
GarageArea      0.000000
GarageYrBlt     0.054795
dtype: float64

In [46]:
x_train['GarageYrBlt'].corr(x_train['YearBuilt'])

np.float64(0.8195574824669842)

In [47]:
x_train.drop('GarageYrBlt', axis=1, inplace=True) # If there is no garage, there is no YearBuilt
x_test.drop('GarageYrBlt', axis=1, inplace=True)

# Handling NaN ( # 3 )

In [48]:
x_train.loc[:,['PoolArea','PoolQC']].isna().mean()
x_train.PoolArea.value_counts()

PoolArea
0      1162
648       1
555       1
480       1
512       1
519       1
738       1
Name: count, dtype: int64

In [49]:
x_train['PoolArea'].corr(x_train['SalePrice'])

np.float64(0.11562969356780654)

In [50]:
x_train.drop('PoolArea', axis=1, inplace=True)
x_train.drop('PoolQC', axis=1, inplace=True)

x_test.drop('PoolArea', axis=1, inplace=True)
x_test.drop('PoolQC', axis=1, inplace=True)

# Handling NaN ( #4 )

In [51]:
x_train.loc[:,['MiscFeature','Alley','Fence','LotFrontage']]

     MiscFeature Alley  Fence  LotFrontage
254          NaN   NaN    NaN         70.0
1066         NaN   NaN    NaN         59.0
638          NaN   NaN  MnPrv         67.0
799          NaN   NaN  MnPrv         60.0
380          NaN  Pave    NaN         50.0
...          ...   ...    ...          ...
1095         NaN   NaN    NaN         78.0
1130         NaN   NaN  MnPrv         65.0
1294         NaN   NaN    NaN         60.0
860          NaN   NaN  GdPrv         55.0
1126         NaN   NaN    NaN         53.0

[1168 rows x 4 columns]

In [52]:
fix_cols = ['MiscFeature','Alley','Fence']
for col in fix_cols:
    x_train.loc[x_train[col].isna(), col] = 'None'
    x_test.loc[x_test[col].isna(), col] = 'None'

In [53]:
x_train.isna().mean().sort_values(ascending=False)

FireplaceQu      0.468322
LotFrontage      0.185788
Electrical       0.000856
MSZoning         0.000000
MSSubClass       0.000000
                   ...
MoSold           0.000000
YrSold           0.000000
SaleType         0.000000
SaleCondition    0.000000
SalePrice        0.000000
Length: 78, dtype: float64

In [54]:
x_train.loc[:,['FireplaceQu','Fireplaces']]

     FireplaceQu  Fireplaces
254          NaN           0
1066          TA           1
638          NaN           0
799           TA           2
380           Gd           1
...          ...         ...
1095          Gd           1
1130          TA           2
1294         NaN           0
860           Gd           1
1126          TA           1

[1168 rows x 2 columns]

In [55]:
x_train.loc[(x_train['Fireplaces'] == 0) & x_train['FireplaceQu'].isna(), ['FireplaceQu']] = 'None'
x_test.loc[(x_test['Fireplaces'] == 0) & x_test['FireplaceQu'].isna(), ['FireplaceQu']] = 'None'

In [56]:
x_train.isna().mean().sort_values(ascending=False)

LotFrontage      0.185788
Electrical       0.000856
MSSubClass       0.000000
MSZoning         0.000000
LotArea          0.000000
                   ...
MoSold           0.000000
YrSold           0.000000
SaleType         0.000000
SaleCondition    0.000000
SalePrice        0.000000
Length: 78, dtype: float64

In [57]:
x_train.loc[:,['LotFrontage','LotArea']]

      LotFrontage  LotArea
254          70.0     8400
1066         59.0     7837
638          67.0     8777
799          60.0     7200
380          50.0     5000
...           ...      ...
1095         78.0     9317
1130         65.0     7804
1294         60.0     8172
860          55.0     7642
1126         53.0     3684

[1168 rows x 2 columns]

In [58]:
x_train['Electrical'].isna()

254     False
1066    False
638     False
799     False
380     False
        ...
1095    False
1130    False
1294    False
860     False
1126    False
Name: Electrical, Length: 1168, dtype: bool

In [59]:
frontage_median = x_train['LotFrontage'].median()
x_train['LotFrontage'].fillna(frontage_median, inplace=True)
x_test['LotFrontage'].fillna(frontage_median, inplace=True)

In [60]:
x_train['Electrical'].fillna(x_train['Electrical'].mode()[0], inplace=True)

In [61]:
x_train.isna().mean()
#x_train['Electrical']

Id               0.0
MSSubClass       0.0
MSZoning         0.0
LotFrontage      0.0
LotArea          0.0
                ...
MoSold           0.0
YrSold           0.0
SaleType         0.0
SaleCondition    0.0
SalePrice        0.0
Length: 78, dtype: float64

# Handling Categorical values ( Ordinal )

In [62]:
x_train.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,3SsnPorch,ScreenPorch,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
254,255,20,RL,70.0,8400,Pave,None,Reg,Lvl,AllPub,...,0,0,None,None,0,6,2010,WD,Normal,145000
1066,1067,60,RL,59.0,7837,Pave,None,IR1,Lvl,AllPub,...,0,0,None,None,0,5,2009,WD,Normal,178000
638,639,30,RL,67.0,8777,Pave,None,Reg,Lvl,AllPub,...,0,0,MnPrv,None,0,5,2008,WD,Normal,85000
799,800,50,RL,60.0,7200,Pave,None,Reg,Lvl,AllPub,...,0,0,MnPrv,None,0,6,2007,WD,Normal,175000
380,381,50,RL,50.0,5000,Pave,Pave,Reg,Lvl,AllPub,...,0,0,None,None,0,5,2010,WD,Normal,127000

In [63]:
quality_map = {'None': 0, 'Po': 1, 'Fa': 2, 'TA': 3, 'Gd': 4, 'Ex': 5}

quality_cols = ['ExterQual', 'ExterCond', 'BsmtQual', 'BsmtCond',
                'HeatingQC', 'KitchenQual', 'FireplaceQu', 'GarageCond', 'GarageQual']

for col in quality_cols:
    x_train[col] = x_train[col].map(quality_map)
    x_test[col] = x_test[col].map(quality_map)

In [64]:
x_train[quality_cols].isnull().sum()

ExterQual      0
ExterCond      0
BsmtQual       0
BsmtCond       0
HeatingQC      0
KitchenQual    0
FireplaceQu    0
GarageCond     0
GarageQual     0
dtype: int64

In [65]:
ordinal_maps = {
    'BsmtExposure': {'None': 0, 'No': 1, 'Mn': 2, 'Av': 3, 'Gd': 4},
    'BsmtFinType1': {'None': 0, 'Unf': 1, 'LwQ': 2, 'Rec': 3, 'BLQ': 4, 'ALQ': 5, 'GLQ': 6},
    'BsmtFinType2': {'None': 0, 'Unf': 1, 'LwQ': 2, 'Rec': 3, 'BLQ': 4, 'ALQ': 5, 'GLQ': 6},
    'GarageFinish': {'None': 0, 'Unf': 1, 'RFn': 2, 'Fin': 3},
    'LotShape':     {'IR3': 1, 'IR2': 2, 'IR1': 3, 'Reg': 4},
    'LandSlope':    {'Sev': 1, 'Mod': 2, 'Gtl': 3},
    'PavedDrive':   {'N': 1, 'P': 2, 'Y': 3},
    'Utilities':    {'ELO': 1, 'NoSeWa': 2, 'NoSewr': 3, 'AllPub': 4},
    'Functional':   {'Sal': 1, 'Sev': 2, 'Maj2': 3, 'Maj1': 4, 'Mod': 5, 'Min2': 6, 'Min1': 7, 'Typ': 8},
    'Electrical':   {'Mix': 1, 'FuseP': 2, 'FuseF': 3, 'FuseA': 4, 'SBrkr': 5},
}

for col, mapping in ordinal_maps.items():
    x_train[col] = x_train[col].map(mapping)
    x_test[col] = x_test[col].map(mapping)

In [66]:
other_qualities = ['BsmtExposure', 'BsmtFinType1', 'BsmtFinType2', 'GarageFinish', 'LotShape', 'LandSlope', 'PavedDrive', 'Utilities', 'Functional', 'Electrical']

x_train[other_qualities].isnull().sum()

BsmtExposure    0
BsmtFinType1    0
BsmtFinType2    0
GarageFinish    0
LotShape        0
LandSlope       0
PavedDrive      0
Utilities       0
Functional      0
Electrical      0
dtype: int64

In [67]:
x_train.dtypes[x_train.dtypes == object]

MSZoning         object
Street           object
Alley            object
LandContour      object
LotConfig        object
Neighborhood     object
Condition1       object
Condition2       object
BldgType         object
HouseStyle       object
RoofStyle        object
RoofMatl         object
Exterior1st      object
Exterior2nd      object
MasVnrType       object
Foundation       object
Heating          object
CentralAir       object
GarageType       object
Fence            object
MiscFeature      object
SaleType         object
SaleCondition    object
dtype: object

In [68]:
fence_map = {'None': 0, 'MnWw': 1, 'GdWo': 2, 'MnPrv': 3, 'GdPrv': 4}

x_train['Fence']= x_train['Fence'].map(fence_map)
x_test['Fence'] = x_test['Fence'].map(fence_map)

# Handling Nominal features

In [69]:
nominal_cols = ['MSSubClass', 'MSZoning', 'Alley', 'LandContour', 'LotConfig',
                'Neighborhood', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle',
                'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
                'Foundation', 'Heating', 'GarageType', 'MiscFeature',
                'SaleType', 'SaleCondition']

x_train[nominal_cols].nunique().sort_values(ascending=False)

Neighborhood     25
Exterior2nd      16
Exterior1st      15
MSSubClass       15
Condition1        9
SaleType          9
Condition2        8
HouseStyle        8
RoofMatl          7
GarageType        7
RoofStyle         6
SaleCondition     6
Foundation        6
Heating           6
BldgType          5
LotConfig         5
MSZoning          5
MiscFeature       5
LandContour       4
MasVnrType        4
Alley             3
dtype: int64

In [70]:
(x_train['Exterior1st'] == x_train['Exterior2nd']).mean()

np.float64(0.8501712328767124)

In [71]:
x_train['HasMultipleExterior'] = (x_train['Exterior1st'] != x_train['Exterior2nd']).astype(int)
x_test['HasMultipleExterior'] = (x_test['Exterior1st'] != x_test['Exterior2nd']).astype(int)

In [72]:
x_train.drop('Exterior2nd', axis=1, inplace=True)
x_test.drop('Exterior2nd', axis=1, inplace=True)

In [73]:
(x_train['Condition1'] == x_train['Condition2']).mean()

np.float64(0.8638698630136986)

In [74]:
x_train['HasMultipleCondition'] = (x_train['Condition1'] != x_train['Condition2']).astype(int)
x_test['HasMultipleCondition'] = (x_test['Condition1'] != x_test['Condition2']).astype(int)

x_train.drop('Condition2', axis=1, inplace=True)
x_test.drop('Condition2', axis=1, inplace=True)

In [75]:
nominal_cols = ['MSSubClass', 'MSZoning', 'Alley', 'LandContour', 'LotConfig',
                'Neighborhood', 'Condition1', 'BldgType', 'HouseStyle',
                'RoofStyle', 'RoofMatl', 'Exterior1st', 'MasVnrType',
                'Foundation', 'Heating', 'GarageType', 'MiscFeature',
                'SaleType', 'SaleCondition']


x_train = pd.get_dummies(x_train,columns=nominal_cols,drop_first=True,dtype=int)
x_test = pd.get_dummies(x_test,columns=nominal_cols,drop_first=True,dtype=int)
x_train, x_test = x_train.align(x_test, join='left', axis=1, fill_value=0)

In [76]:
x_train.dtypes == object

Id                       False
LotFrontage              False
LotArea                  False
Street                    True
LotShape                 False
                         ...
SaleCondition_AdjLand    False
SaleCondition_Alloca     False
SaleCondition_Family     False
SaleCondition_Normal     False
SaleCondition_Partial    False
Length: 190, dtype: bool

In [77]:
x_train['Street'] = x_train['Street'].map({'Grvl': 0, 'Pave': 1})
x_test['Street'] = x_test['Street'].map({'Grvl': 0, 'Pave': 1})

x_train['CentralAir'] = x_train['CentralAir'].map({'N': 0, 'Y': 1})
x_test['CentralAir'] = x_test['CentralAir'].map({'N': 0, 'Y': 1})

In [78]:
x_train.dtypes

Id                         int64
LotFrontage              float64
LotArea                    int64
Street                     int64
LotShape                   int64
                          ...
SaleCondition_AdjLand      int64
SaleCondition_Alloca       int64
SaleCondition_Family       int64
SaleCondition_Normal       int64
SaleCondition_Partial      int64
Length: 190, dtype: object

# Training Model

In [81]:
x_train.drop('Id',axis=1,inplace=True)
x_test.drop('Id',axis=1,inplace=True)


y_train = np.log1p(x_train['SalePrice'])
x_train = x_train.drop('SalePrice', axis=1)

y_test = np.log1p(x_test['SalePrice'])
x_test = x_test.drop('SalePrice', axis=1)

In [206]:
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler,MinMaxScaler,RobustScaler
from sklearn.model_selection import KFold,GridSearchCV

kf = KFold(n_splits=5, shuffle=True, random_state=42)

pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('linear_model', LinearRegression()),
])

param_grid = {
    'scaler' : [StandardScaler(),MinMaxScaler(),RobustScaler()],
}

grid_search = GridSearchCV(
    pipeline,
    param_grid=param_grid,
    cv=kf,
    scoring='neg_mean_squared_error',
    verbose=2,
    return_train_score=True,
)

In [207]:
grid_search.fit(x_train, y_train)

print(f'Best scaler: {grid_search.best_params_["scaler"]}')
print(f'Best RMSE: {-grid_search.best_score_:.4f}')

Fitting 5 folds for each of 3 candidates, totalling 15 fits
[CV] END ............................scaler=StandardScaler(); total time=   0.0s
[CV] END ............................scaler=StandardScaler(); total time=   0.0s
[CV] END ............................scaler=StandardScaler(); total time=   0.0s
[CV] END ............................scaler=StandardScaler(); total time=   0.0s
[CV] END ............................scaler=StandardScaler(); total time=   0.0s
[CV] END ..............................scaler=MinMaxScaler(); total time=   0.0s
[CV] END ..............................scaler=MinMaxScaler(); total time=   0.0s
[CV] END ..............................scaler=MinMaxScaler(); total time=   0.0s
[CV] END ..............................scaler=MinMaxScaler(); total time=   0.0s
[CV] END ..............................scaler=MinMaxScaler(); total time=   0.0s
[CV] END ..............................scaler=RobustScaler(); total time=   0.1s
[CV] END ..............................scaler=RobustScaler(); total time=   0.1s
[CV] END ..............................scaler=RobustScaler(); total time=   0.1s
[CV] END ..............................scaler=RobustScaler(); total time=   0.1s
[CV] END ..............................scaler=RobustScaler(); total time=   0.1s
Best scaler: StandardScaler()
Best RMSE: 0.0293

## Correlation Filter

In [208]:
corr_matrix = np.abs(x_train.corr())

In [209]:
mask = np.triu(np.ones_like(corr_matrix, dtype=bool))

In [210]:
threshold = 0.6
high_corr_pairs = []

for i in range(len(corr_matrix.columns)):
    for j in range(i+1, len(corr_matrix.columns)):
        if corr_matrix.iloc[i, j] > threshold:
            high_corr_pairs.append((corr_matrix.columns[i], corr_matrix.columns[j], corr_matrix.iloc[i, j]))

# Display highly correlated pairs
if high_corr_pairs:
    print("Highly correlated feature pairs:")
    for feat1, feat2, corr in high_corr_pairs:
        print(f"{feat1} and {feat2}: {corr:.4f}")
else:
    print(f"No feature pairs with correlation above {threshold} found.")

Highly correlated feature pairs:
OverallQual and ExterQual: 0.7111
OverallQual and BsmtQual: 0.6301
OverallQual and KitchenQual: 0.6796
YearBuilt and BsmtQual: 0.6030
YearBuilt and Foundation_PConc: 0.6333
YearRemodAdd and KitchenQual: 0.6300
MasVnrArea and MasVnrType_None: 0.7033
ExterQual and KitchenQual: 0.7162
BsmtQual and BsmtCond: 0.6207
BsmtCond and Foundation_Slab: 0.7132
BsmtFinType1 and BsmtFinSF1: 0.6886
BsmtFinSF1 and BsmtFullBath: 0.6490
BsmtFinType2 and BsmtFinSF2: 0.7878
TotalBsmtSF and 1stFlrSF: 0.8274
2ndFlrSF and GrLivArea: 0.6875
2ndFlrSF and TotRmsAbvGrd: 0.6223
2ndFlrSF and MSSubClass_60: 0.6786
2ndFlrSF and HouseStyle_1Story: 0.7898
2ndFlrSF and HouseStyle_2Story: 0.8032
LowQualFinSF and HouseStyle_2.5Fin: 0.6324
GrLivArea and FullBath: 0.6178
GrLivArea and TotRmsAbvGrd: 0.8207
HalfBath and MSSubClass_60: 0.6036
HalfBath and HouseStyle_2Story: 0.6216
BedroomAbvGr and TotRmsAbvGrd: 0.6789
KitchenAbvGr and MSSubClass_90: 0.6200
KitchenAbvGr and BldgType_Duplex: 0.6200
Fireplaces and FireplaceQu: 0.8589
GarageCars and GarageArea: 0.8825
GarageQual and GarageCond: 0.9594
GarageQual and GarageType_None: 0.9417
GarageCond and GarageType_None: 0.9456
HasMultipleCondition and Condition1_Feedr: 0.6057
HasMultipleCondition and Condition1_Norm: 0.9822
MSSubClass_45 and HouseStyle_1.5Unf: 0.9121
MSSubClass_60 and HouseStyle_2Story: 0.7573
MSSubClass_75 and HouseStyle_2.5Unf: 0.6974
MSSubClass_80 and HouseStyle_SLvl: 0.9274
MSSubClass_85 and HouseStyle_SFoyer: 0.7755
MSSubClass_90 and BldgType_Duplex: 1.0000
MSSubClass_120 and BldgType_TwnhsE: 0.7865
MSSubClass_160 and BldgType_Twnhs: 0.6189
MSSubClass_190 and BldgType_2fmCon: 0.9822
MSZoning_FV and Neighborhood_Somerst: 0.8701
MSZoning_RL and MSZoning_RM: 0.8087
MSZoning_RM and Neighborhood_OldTown: 0.6003
Alley_None and Alley_Pave: 0.6243
Condition1_Feedr and Condition1_Norm: 0.6055
HouseStyle_1Story and HouseStyle_2Story: 0.6595
RoofStyle_Gable and RoofStyle_Hip: 0.9333
RoofMatl_CompShg and RoofMatl_Tar&Grv: 0.6853
MasVnrType_BrkFace and MasVnrType_None: 0.8026
Foundation_CBlock and Foundation_PConc: 0.7805
Heating_GasA and Heating_GasW: 0.7278
GarageType_Attchd and GarageType_Detchd: 0.7228
MiscFeature_None and MiscFeature_Shed: 0.9420
SaleType_New and SaleType_WD: 0.7665
SaleType_New and SaleCondition_Normal: 0.6542
SaleType_New and SaleCondition_Partial: 0.9944
SaleType_WD and SaleCondition_Normal: 0.6546
SaleType_WD and SaleCondition_Partial: 0.7708
SaleCondition_Normal and SaleCondition_Partial: 0.6579

In [211]:
# Create a mask for the upper triangle
mask = np.triu(np.ones_like(corr_matrix, dtype=bool))

# Find feature pairs with correlation greater than a threshold
threshold = 0.7
high_corr_pairs = []

for i in range(len(corr_matrix.columns)):
    for j in range(i+1, len(corr_matrix.columns)):
        if corr_matrix.iloc[i, j] > threshold:
            high_corr_pairs.append((corr_matrix.columns[i], corr_matrix.columns[j], corr_matrix.iloc[i, j]))

# Display highly correlated pairs
if high_corr_pairs:
    print("Highly correlated feature pairs:")
    for feat1, feat2, corr in high_corr_pairs:
        print(f"{feat1} and {feat2}: {corr:.4f}")
else:
    print(f"No feature pairs with correlation above {threshold} found.")

# To remove one feature from each highly correlated pair
# (typically the one with lower correlation with target)
features_to_drop = []
for feat1, feat2, _ in high_corr_pairs:
    # Compare correlation with target
    if abs(x_train[feat1].corr(y_train)) < abs(x_train[feat2].corr(y_train)):
        features_to_drop.append(feat1)
    else:
        features_to_drop.append(feat2)

# Remove duplicates
features_to_drop = list(set(features_to_drop))
print(f"Features to drop due to high correlation: {features_to_drop}")

# Create filtered dataset
X_filtered = x_train.drop(columns=features_to_drop)
print(f"Original shape: {x_train.shape}, New shape: {X_filtered.shape}")

Highly correlated feature pairs:
OverallQual and ExterQual: 0.7111
MasVnrArea and MasVnrType_None: 0.7033
ExterQual and KitchenQual: 0.7162
BsmtCond and Foundation_Slab: 0.7132
BsmtFinType2 and BsmtFinSF2: 0.7878
TotalBsmtSF and 1stFlrSF: 0.8274
2ndFlrSF and HouseStyle_1Story: 0.7898
2ndFlrSF and HouseStyle_2Story: 0.8032
GrLivArea and TotRmsAbvGrd: 0.8207
Fireplaces and FireplaceQu: 0.8589
GarageCars and GarageArea: 0.8825
GarageQual and GarageCond: 0.9594
GarageQual and GarageType_None: 0.9417
GarageCond and GarageType_None: 0.9456
HasMultipleCondition and Condition1_Norm: 0.9822
MSSubClass_45 and HouseStyle_1.5Unf: 0.9121
MSSubClass_60 and HouseStyle_2Story: 0.7573
MSSubClass_80 and HouseStyle_SLvl: 0.9274
MSSubClass_85 and HouseStyle_SFoyer: 0.7755
MSSubClass_90 and BldgType_Duplex: 1.0000
MSSubClass_120 and BldgType_TwnhsE: 0.7865
MSSubClass_190 and BldgType_2fmCon: 0.9822
MSZoning_FV and Neighborhood_Somerst: 0.8701
MSZoning_RL and MSZoning_RM: 0.8087
RoofStyle_Gable and RoofStyle_Hip: 0.9333
MasVnrType_BrkFace and MasVnrType_None: 0.8026
Foundation_CBlock and Foundation_PConc: 0.7805
Heating_GasA and Heating_GasW: 0.7278
GarageType_Attchd and GarageType_Detchd: 0.7228
MiscFeature_None and MiscFeature_Shed: 0.9420
SaleType_New and SaleType_WD: 0.7665
SaleType_New and SaleCondition_Partial: 0.9944
SaleType_WD and SaleCondition_Partial: 0.7708
Features to drop due to high correlation: ['GarageType_Detchd', 'MSSubClass_80', 'BldgType_Duplex', 'MSZoning_RL', 'TotRmsAbvGrd', 'SaleType_New', 'GarageCond', 'MSZoning_FV', 'HasMultipleCondition', 'Fireplaces', 'BsmtFinSF2', 'RoofStyle_Gable', 'MSSubClass_85', 'GarageArea', 'MSSubClass_190', 'Heating_GasW', 'MasVnrType_None', 'Foundation_CBlock', 'GarageType_None', 'HouseStyle_1Story', 'SaleType_WD', 'ExterQual', 'BldgType_TwnhsE', 'MasVnrType_BrkFace', 'MSSubClass_45', 'Foundation_Slab', '1stFlrSF', 'HouseStyle_2Story', 'MiscFeature_Shed']
Original shape: (1168, 188), New shape: (1168, 159)

## RFE

In [212]:
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import RFE
from sklearn.linear_model import LinearRegression

scaler = StandardScaler()
x_train_scaled = pd.DataFrame(scaler.fit_transform(x_train), columns=x_train.columns)

model = LinearRegression()
rfe = RFE(estimator=model,n_features_to_select=100,step=1)
rfe.fit(x_train_scaled, y_train)

rfe_selected_features = x_train.columns[rfe.support_].tolist()

print("Features selected by RFE:")
print("Features selected by RFE:")
for i, feature in enumerate(rfe_selected_features, 1):
    print(f"{i}. {feature}")

Features selected by RFE:
Features selected by RFE:
1. LotFrontage
2. LotArea
3. OverallQual
4. OverallCond
5. YearBuilt
6. YearRemodAdd
7. BsmtQual
8. BsmtExposure
9. BsmtFinType1
10. BsmtFinSF1
11. TotalBsmtSF
12. HeatingQC
13. CentralAir
14. 1stFlrSF
15. 2ndFlrSF
16. LowQualFinSF
17. GrLivArea
18. BsmtFullBath
19. FullBath
20. HalfBath
21. KitchenAbvGr
22. KitchenQual
23. TotRmsAbvGrd
24. Functional
25. Fireplaces
26. GarageCars
27. GarageArea
28. GarageQual
29. GarageCond
30. WoodDeckSF
31. 3SsnPorch
32. ScreenPorch
33. MiscVal
34. HasMultipleCondition
35. MSSubClass_30
36. MSSubClass_45
37. MSSubClass_60
38. MSSubClass_160
39. MSZoning_FV
40. MSZoning_RH
41. MSZoning_RL
42. MSZoning_RM
43. Alley_Pave
44. LandContour_HLS
45. LandContour_Lvl
46. LotConfig_CulDSac
47. Neighborhood_BrkSide
48. Neighborhood_ClearCr
49. Neighborhood_Crawfor
50. Neighborhood_MeadowV
51. Neighborhood_NPkVill
52. Neighborhood_NoRidge
53. Neighborhood_NridgHt
54. Neighborhood_Somerst
55. Neighborhood_StoneBr
56. Neighborhood_Timber
57. Neighborhood_Veenker
58. Condition1_Norm
59. Condition1_RRAn
60. BldgType_Duplex
61. BldgType_Twnhs
62. BldgType_TwnhsE
63. HouseStyle_1.5Unf
64. HouseStyle_1Story
65. HouseStyle_2.5Fin
66. HouseStyle_2.5Unf
67. HouseStyle_2Story
68. RoofStyle_Gable
69. RoofStyle_Gambrel
70. RoofStyle_Hip
71. RoofMatl_CompShg
72. RoofMatl_Metal
73. RoofMatl_Roll
74. RoofMatl_Tar&Grv
75. RoofMatl_WdShake
76. RoofMatl_WdShngl
77. Exterior1st_BrkComm
78. Exterior1st_BrkFace
79. MasVnrType_BrkFace
80. MasVnrType_None
81. MasVnrType_Stone
82. Foundation_PConc
83. Heating_GasA
84. Heating_GasW
85. Heating_Grav
86. Heating_Wall
87. GarageType_Attchd
88. GarageType_Basment
89. GarageType_BuiltIn
90. GarageType_CarPort
91. GarageType_Detchd
92. GarageType_None
93. MiscFeature_None
94. MiscFeature_Shed
95. SaleType_ConLD
96. SaleType_New
97. SaleType_Oth
98. SaleCondition_Alloca
99. SaleCondition_Normal
100. SaleCondition_Partial

In [213]:
x_train_rfe = x_train.copy()

for cols in x_train_rfe:
    if cols not in rfe_selected_features:
        x_train_rfe.drop(cols, axis=1, inplace=True)

In [214]:
x_train_rfe.head()

,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,BsmtQual,BsmtExposure,BsmtFinType1,BsmtFinSF1,...,GarageType_Detchd,GarageType_None,MiscFeature_None,MiscFeature_Shed,SaleType_ConLD,SaleType_New,SaleType_Oth,SaleCondition_Alloca,SaleCondition_Normal,SaleCondition_Partial
254,70.0,8400,5,6,1957,1957,3,1,3,922,...,0,0,1,0,0,0,0,0,1,0
1066,59.0,7837,6,7,1993,1994,4,1,1,0,...,0,0,1,0,0,0,0,0,1,0
638,67.0,8777,5,7,1910,1950,2,1,1,0,...,0,1,1,0,0,0,0,0,1,0
799,60.0,7200,5,7,1937,1950,4,1,5,569,...,1,0,1,0,0,0,0,0,1,0
380,50.0,5000,5,6,1924,1950,3,1,2,218,...,1,0,1,0,0,0,0,0,1,0

In [215]:
def train_and_evaluate(X, y, cv=kf):
    pipeline = Pipeline([
        ('scaler', StandardScaler()),
        ('model', LinearRegression()),
    ])

    param_grid = {
        'scaler': [StandardScaler(), MinMaxScaler(), RobustScaler()],
    }

    grid_search = GridSearchCV(
        pipeline,
        param_grid=param_grid,
        cv=cv,
        scoring='neg_root_mean_squared_error',
        return_train_score=True,
    )

    grid_search.fit(X, y)
    return grid_search

In [89]:
train_and_evaluate(x_train_rfe, y_train)

Best scaler: StandardScaler()
Train RMSE:  0.0979
Val RMSE:    0.1526 (+/- 0.0327)
Overfit gap: 0.0547
Features:    100

GridSearchCV(cv=KFold(n_splits=5, random_state=42, shuffle=True),
             estimator=Pipeline(steps=[('scaler', StandardScaler()),
                                       ('model', LinearRegression())]),
             param_grid={'scaler': [StandardScaler(), MinMaxScaler(),
                                    RobustScaler()]},
             return_train_score=True, scoring='neg_root_mean_squared_error')

In [90]:
train_and_evaluate(X_filtered, y_train)

Best scaler: StandardScaler()
Train RMSE:  0.1002
Val RMSE:    0.1431 (+/- 0.0303)
Overfit gap: 0.0429
Features:    159

GridSearchCV(cv=KFold(n_splits=5, random_state=42, shuffle=True),
             estimator=Pipeline(steps=[('scaler', StandardScaler()),
                                       ('model', LinearRegression())]),
             param_grid={'scaler': [StandardScaler(), MinMaxScaler(),
                                    RobustScaler()]},
             return_train_score=True, scoring='neg_root_mean_squared_error')

In [91]:
train_and_evaluate(x_test,y_test)

Best scaler: RobustScaler()
Train RMSE:  0.0490
Val RMSE:    0.2263 (+/- 0.0282)
Overfit gap: 0.1773
Features:    188

GridSearchCV(cv=KFold(n_splits=5, random_state=42, shuffle=True),
             estimator=Pipeline(steps=[('scaler', StandardScaler()),
                                       ('model', LinearRegression())]),
             param_grid={'scaler': [StandardScaler(), MinMaxScaler(),
                                    RobustScaler()]},
             return_train_score=True, scoring='neg_root_mean_squared_error')

# Logging model information

In [219]:
import dagshub
import mlflow
import importlib
import feature_eng
importlib.reload(feature_eng)
from feature_eng import preprocess

from sklearn.metrics import root_mean_squared_error
dagshub.init(repo_owner='ldavi22', repo_name='cs229-231', mlflow=True)

df = pd.read_csv("~/ML/Data/house_prices/train.csv")
x_train,x_test = train_test_split(df,test_size=0.2,random_state=42)
x_train,x_test,y_train,y_test = preprocess(x_train,x_test)

mlflow.set_tracking_uri("https://dagshub.com/ldavi22/cs229-231.mlflow")
mlflow.set_experiment('house-prices-linear-regression_')

def log_experiment(name,x_train,y_train,x_test,y_test,params=None):
    x_test = x_test[x_train.columns]
    with mlflow.start_run(run_name=name):

        result = train_and_evaluate(x_train, y_train)

        test_pred = result.best_estimator_.predict(x_test)
        test_rmse = root_mean_squared_error(y_test,test_pred)

        best_idx = result.best_index_
        train_rmse = -result.cv_results_['mean_train_score'][best_idx]
        val_rmse = -result.best_score_
        val_std = result.cv_results_['std_test_score'][best_idx]

        mlflow.log_param("model", "LinearRegression")
        mlflow.log_param("best_scaler", str(result.best_params_['scaler']))
        mlflow.log_param("n_features", x_train.shape[1])
        mlflow.log_param("n_samples", x_train.shape[0])
        mlflow.log_param("feature_selection", name)

        for key,value in result.best_params_.items():
            mlflow.log_param(key, value)

        if params:
            for k,v in params.items():
                mlflow.log_param(k,v)

        mlflow.log_metric("train_rmse", train_rmse)
        mlflow.log_metric("val_rmse", val_rmse)
        mlflow.log_metric("test_rmse", test_rmse)
        mlflow.log_metric("val_std", val_std)
        mlflow.log_metric("overfit_gap", val_rmse - train_rmse)

    return result

iter_0 = log_experiment("Ordinary Least Squares with all features", x_train, y_train,x_test, y_test)

iter_1 = log_experiment("Least squares with features filtered with correlation",X_filtered,y_train,x_test, y_test)

iter_2 = log_experiment("Least squares with features filtered with RFE",x_train_rfe,y_train,x_test, y_test)

Initialized MLflow to track repo "ldavi22/cs229-231"

Repository ldavi22/cs229-231 initialized!

🏃 View run Ordinary Least Squares with all features at: https://dagshub.com/ldavi22/cs229-231.mlflow/#/experiments/1/runs/2d122d6f072e45d1bb4521ef7d9cef9a
🧪 View experiment at: https://dagshub.com/ldavi22/cs229-231.mlflow/#/experiments/1
🏃 View run Least squares with features filtered with correlation at: https://dagshub.com/ldavi22/cs229-231.mlflow/#/experiments/1/runs/3d99c528cb34429abeeb2c16c5198394
🧪 View experiment at: https://dagshub.com/ldavi22/cs229-231.mlflow/#/experiments/1
🏃 View run Least squares with features filtered with RFE at: https://dagshub.com/ldavi22/cs229-231.mlflow/#/experiments/1/runs/b796fa7f031b4b90bc77e55bc4aaa63a
🧪 View experiment at: https://dagshub.com/ldavi22/cs229-231.mlflow/#/experiments/1

In [123]:
from sklearn.linear_model import Ridge , Lasso
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler,MinMaxScaler,RobustScaler
from sklearn.model_selection import KFold,GridSearchCV

kf = KFold(n_splits=5, shuffle=True, random_state=42)

pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('model', Ridge()),
    ])

param_grid = {
    'scaler': [StandardScaler(), MinMaxScaler(), RobustScaler()],
    'model__alpha' : [0.5,1,2,5,10,100],
    }

grid_search = GridSearchCV(
    pipeline,
    param_grid=param_grid,
    cv=kf,
    scoring='neg_root_mean_squared_error',
    return_train_score=True,
    )

In [124]:
result = grid_search.fit(x_train, y_train)

In [94]:
print("Best parameters found: ", grid_search.best_params_)
print(f'Best RMSE: {-grid_search.best_score_:.4f}')

Best parameters found:  {'model__alpha': 5, 'scaler': MinMaxScaler()}
Best RMSE: 0.1392

In [125]:
with mlflow.start_run(run_name="Ridge Regression"):

    best_idx = result.best_index_
    train_rmse = -result.cv_results_['mean_train_score'][best_idx]
    val_rmse = -result.best_score_
    val_std = result.cv_results_['std_test_score'][best_idx]
    train_rmse = (-result.cv_results_['mean_train_score'][best_idx])
    val_rmse = (-result.best_score_)

    for key,value in result.best_params_.items():
        mlflow.log_param(key, value)

    mlflow.log_param("model", "LinearRegression")
    mlflow.log_param("best_scaler", str(result.best_params_['scaler']))
    mlflow.log_param("n_features", x_train.shape[1])
    mlflow.log_param("n_samples", x_train.shape[0])
    mlflow.log_param("feature_selection", "Ridge Regression")

    mlflow.log_metric("train_rmse", train_rmse)
    mlflow.log_metric("val_rmse", val_rmse)
    mlflow.log_metric("test_rmse", val_rmse)
    mlflow.log_metric("val_std", val_std)
    mlflow.log_metric("overfit_gap", val_rmse - train_rmse)

🏃 View run Ridge Regression at: https://dagshub.com/ldavi22/cs229-231.mlflow/#/experiments/1/runs/1575cce1bfd14c6daf3f074168e3f61b
🧪 View experiment at: https://dagshub.com/ldavi22/cs229-231.mlflow/#/experiments/1

In [79]:
from sklearn.linear_model import Lasso
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler,MinMaxScaler,RobustScaler
from sklearn.model_selection import KFold,GridSearchCV
kf = KFold(n_splits=5, shuffle=True, random_state=42)

pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('model', Lasso()),
    ])

param_grid = {
    'scaler': [StandardScaler(), MinMaxScaler(), RobustScaler()],
    'model__alpha' : [0.5,1,2,5,10,100],
    }

grid_search = GridSearchCV(
    pipeline,
    param_grid=param_grid,
    cv=kf,
    scoring='neg_root_mean_squared_error',
    return_train_score=True,
    )

In [82]:
result = grid_search.fit(x_train, y_train)

In [97]:
from logging_helper import log
from feature_eng import preprocess

#x_train, x_test, y_train, y_test = preprocess(x_train,x_test)
log(x_train,y_train,x_test[x_train.columns],y_test,result,"Lasso Regression")

Initialized MLflow to track repo "ldavi22/cs229-231"

Repository ldavi22/cs229-231 initialized!

🏃 View run Lasso Regression at: https://dagshub.com/ldavi22/cs229-231.mlflow/#/experiments/1/runs/20577aa07cc2409ab97bc5e040ddcc61
🧪 View experiment at: https://dagshub.com/ldavi22/cs229-231.mlflow/#/experiments/1

ValueError: The feature names should match those that were passed during fit.
Feature names unseen at fit time:
- RoofMatl_Membran